import type { People } from '../../interfaces'

export const mockedPeople: People[] = [
  {
    name: 'Luke Skywalker',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person2',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person3',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person4',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person5',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person6',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person7',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person8',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person9',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person10',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person11',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person12',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
]
