import type { People } from '../../interfaces'

export const MOCKED_LUKE_PERSON = {
  name: 'Luke Skywalker',
  height: '172',
  mass: '77',
  hair_color: 'blond',
  skin_color: 'fair',
  eye_color: 'blue',
  birth_year: '19BBY',
  gender: 'male',
  homeworld: 'https://swapi.info/api/planets/1',
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/6',
  ],
  species: [],
  vehicles: [
    'https://swapi.info/api/vehicles/14',
    'https://swapi.info/api/vehicles/30',
  ],
  starships: [
    'https://swapi.info/api/starships/12',
    'https://swapi.info/api/starships/22',
  ],
  created: '2014-12-20T21:17:56.891000Z',
  url: 'https://swapi.info/api/people/1',
}

export const mockedPeople: People[] = [
  MOCKED_LUKE_PERSON,
  {
    name: 'Person2',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person3',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person4',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person5',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person6',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person7',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person8',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person9',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person10',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-25T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person11',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person12',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-01T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
]

export const FILTERED_PEOPLE_TEST_CASES = [
  {
    searchedName: 'Person1',
    expected: [
      {
        birth_year: '19BBY',
        created: '2014-12-25T21:17:56.891000Z',
        eye_color: 'blue',
        films: [
          'https://swapi.info/api/films/1',
          'https://swapi.info/api/films/2',
          'https://swapi.info/api/films/3',
          'https://swapi.info/api/films/6',
        ],
        gender: 'male',
        hair_color: 'blond',
        height: '172',
        homeworld: 'https://swapi.info/api/planets/1',
        mass: '77',
        name: 'Person10',
        skin_color: 'fair',
        species: [],
        starships: [
          'https://swapi.info/api/starships/12',
          'https://swapi.info/api/starships/22',
        ],
        url: 'https://swapi.info/api/people/1',
        vehicles: [
          'https://swapi.info/api/vehicles/14',
          'https://swapi.info/api/vehicles/30',
        ],
      },
      {
        birth_year: '19BBY',
        created: '2014-12-20T21:17:56.891000Z',
        eye_color: 'blue',
        films: [
          'https://swapi.info/api/films/1',
          'https://swapi.info/api/films/2',
          'https://swapi.info/api/films/3',
          'https://swapi.info/api/films/6',
        ],
        gender: 'male',
        hair_color: 'blond',
        height: '172',
        homeworld: 'https://swapi.info/api/planets/1',
        mass: '77',
        name: 'Person11',
        skin_color: 'fair',
        species: [],
        starships: [
          'https://swapi.info/api/starships/12',
          'https://swapi.info/api/starships/22',
        ],
        url: 'https://swapi.info/api/people/1',
        vehicles: [
          'https://swapi.info/api/vehicles/14',
          'https://swapi.info/api/vehicles/30',
        ],
      },
      {
        birth_year: '19BBY',
        created: '2014-12-01T21:17:56.891000Z',
        eye_color: 'blue',
        films: [
          'https://swapi.info/api/films/1',
          'https://swapi.info/api/films/2',
          'https://swapi.info/api/films/3',
          'https://swapi.info/api/films/6',
        ],
        gender: 'male',
        hair_color: 'blond',
        height: '172',
        homeworld: 'https://swapi.info/api/planets/1',
        mass: '77',
        name: 'Person12',
        skin_color: 'fair',
        species: [],
        starships: [
          'https://swapi.info/api/starships/12',
          'https://swapi.info/api/starships/22',
        ],
        url: 'https://swapi.info/api/people/1',
        vehicles: [
          'https://swapi.info/api/vehicles/14',
          'https://swapi.info/api/vehicles/30',
        ],
      },
    ],
  },
  {
    searchedName: 'LUKE',
    expected: [MOCKED_LUKE_PERSON],
  },
]

export const FILTERED_SORTED_PEOPLE_TEST_CASES = [
  {
    searchedName: 'Person1',
    expected: [
      {
        birth_year: '19BBY',
        created: '2014-12-01T21:17:56.891000Z',
        eye_color: 'blue',
        films: [
          'https://swapi.info/api/films/1',
          'https://swapi.info/api/films/2',
          'https://swapi.info/api/films/3',
          'https://swapi.info/api/films/6',
        ],
        gender: 'male',
        hair_color: 'blond',
        height: '172',
        homeworld: 'https://swapi.info/api/planets/1',
        mass: '77',
        name: 'Person12',
        skin_color: 'fair',
        species: [],
        starships: [
          'https://swapi.info/api/starships/12',
          'https://swapi.info/api/starships/22',
        ],
        url: 'https://swapi.info/api/people/1',
        vehicles: [
          'https://swapi.info/api/vehicles/14',
          'https://swapi.info/api/vehicles/30',
        ],
      },
      {
        birth_year: '19BBY',
        created: '2014-12-20T21:17:56.891000Z',
        eye_color: 'blue',
        films: [
          'https://swapi.info/api/films/1',
          'https://swapi.info/api/films/2',
          'https://swapi.info/api/films/3',
          'https://swapi.info/api/films/6',
        ],
        gender: 'male',
        hair_color: 'blond',
        height: '172',
        homeworld: 'https://swapi.info/api/planets/1',
        mass: '77',
        name: 'Person11',
        skin_color: 'fair',
        species: [],
        starships: [
          'https://swapi.info/api/starships/12',
          'https://swapi.info/api/starships/22',
        ],
        url: 'https://swapi.info/api/people/1',
        vehicles: [
          'https://swapi.info/api/vehicles/14',
          'https://swapi.info/api/vehicles/30',
        ],
      },
      {
        birth_year: '19BBY',
        created: '2014-12-25T21:17:56.891000Z',
        eye_color: 'blue',
        films: [
          'https://swapi.info/api/films/1',
          'https://swapi.info/api/films/2',
          'https://swapi.info/api/films/3',
          'https://swapi.info/api/films/6',
        ],
        gender: 'male',
        hair_color: 'blond',
        height: '172',
        homeworld: 'https://swapi.info/api/planets/1',
        mass: '77',
        name: 'Person10',
        skin_color: 'fair',
        species: [],
        starships: [
          'https://swapi.info/api/starships/12',
          'https://swapi.info/api/starships/22',
        ],
        url: 'https://swapi.info/api/people/1',
        vehicles: [
          'https://swapi.info/api/vehicles/14',
          'https://swapi.info/api/vehicles/30',
        ],
      },
    ],
  },
  {
    searchedName: 'LUKE',
    expected: [MOCKED_LUKE_PERSON],
  },
]

export const EXPECTED_SORTED_PEOPLE_NAME_ASCENDING = [
  MOCKED_LUKE_PERSON,
  {
    name: 'Person10',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-25T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person11',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person12',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-01T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person2',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person3',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person4',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person5',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person6',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person7',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person8',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  {
    name: 'Person9',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
]

export const EXPECTED_SORTED_PEOPLE_NAME_DESCENDING = [...EXPECTED_SORTED_PEOPLE_NAME_ASCENDING].reverse()

export const EXPECTED_SORTED_PEOPLE_DATE_ASCENDING = [
  {
    name: 'Person12',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-01T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
  MOCKED_LUKE_PERSON, {
    name: 'Person2',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  }, {
    name: 'Person3',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  }, {
    name: 'Person4',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  }, {
    name: 'Person5',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  }, {
    name: 'Person6',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  }, {
    name: 'Person7',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  }, {
    name: 'Person8',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  }, {
    name: 'Person9',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  }, {
    name: 'Person11',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  }, {
    name: 'Person10',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.info/api/planets/1',
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/2',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/6',
    ],
    species: [],
    vehicles: [
      'https://swapi.info/api/vehicles/14',
      'https://swapi.info/api/vehicles/30',
    ],
    starships: [
      'https://swapi.info/api/starships/12',
      'https://swapi.info/api/starships/22',
    ],
    created: '2014-12-25T21:17:56.891000Z',
    url: 'https://swapi.info/api/people/1',
  },
]

export const EXPECTED_SORTED_PEOPLE_DATE_DESCENDING = [{
  name: 'Person10',
  height: '172',
  mass: '77',
  hair_color: 'blond',
  skin_color: 'fair',
  eye_color: 'blue',
  birth_year: '19BBY',
  gender: 'male',
  homeworld: 'https://swapi.info/api/planets/1',
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/6',
  ],
  species: [],
  vehicles: [
    'https://swapi.info/api/vehicles/14',
    'https://swapi.info/api/vehicles/30',
  ],
  starships: [
    'https://swapi.info/api/starships/12',
    'https://swapi.info/api/starships/22',
  ],
  created: '2014-12-25T21:17:56.891000Z',
  url: 'https://swapi.info/api/people/1',
}, {
  name: 'Luke Skywalker',
  height: '172',
  mass: '77',
  hair_color: 'blond',
  skin_color: 'fair',
  eye_color: 'blue',
  birth_year: '19BBY',
  gender: 'male',
  homeworld: 'https://swapi.info/api/planets/1',
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/6',
  ],
  species: [],
  vehicles: [
    'https://swapi.info/api/vehicles/14',
    'https://swapi.info/api/vehicles/30',
  ],
  starships: [
    'https://swapi.info/api/starships/12',
    'https://swapi.info/api/starships/22',
  ],
  created: '2014-12-20T21:17:56.891000Z',
  url: 'https://swapi.info/api/people/1',
}, {
  name: 'Person2',
  height: '172',
  mass: '77',
  hair_color: 'blond',
  skin_color: 'fair',
  eye_color: 'blue',
  birth_year: '19BBY',
  gender: 'male',
  homeworld: 'https://swapi.info/api/planets/1',
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/6',
  ],
  species: [],
  vehicles: [
    'https://swapi.info/api/vehicles/14',
    'https://swapi.info/api/vehicles/30',
  ],
  starships: [
    'https://swapi.info/api/starships/12',
    'https://swapi.info/api/starships/22',
  ],
  created: '2014-12-20T21:17:56.891000Z',
  url: 'https://swapi.info/api/people/1',
}, {
  name: 'Person3',
  height: '172',
  mass: '77',
  hair_color: 'blond',
  skin_color: 'fair',
  eye_color: 'blue',
  birth_year: '19BBY',
  gender: 'male',
  homeworld: 'https://swapi.info/api/planets/1',
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/6',
  ],
  species: [],
  vehicles: [
    'https://swapi.info/api/vehicles/14',
    'https://swapi.info/api/vehicles/30',
  ],
  starships: [
    'https://swapi.info/api/starships/12',
    'https://swapi.info/api/starships/22',
  ],
  created: '2014-12-20T21:17:56.891000Z',
  url: 'https://swapi.info/api/people/1',
}, {
  name: 'Person4',
  height: '172',
  mass: '77',
  hair_color: 'blond',
  skin_color: 'fair',
  eye_color: 'blue',
  birth_year: '19BBY',
  gender: 'male',
  homeworld: 'https://swapi.info/api/planets/1',
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/6',
  ],
  species: [],
  vehicles: [
    'https://swapi.info/api/vehicles/14',
    'https://swapi.info/api/vehicles/30',
  ],
  starships: [
    'https://swapi.info/api/starships/12',
    'https://swapi.info/api/starships/22',
  ],
  created: '2014-12-20T21:17:56.891000Z',
  url: 'https://swapi.info/api/people/1',
}, {
  name: 'Person5',
  height: '172',
  mass: '77',
  hair_color: 'blond',
  skin_color: 'fair',
  eye_color: 'blue',
  birth_year: '19BBY',
  gender: 'male',
  homeworld: 'https://swapi.info/api/planets/1',
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/6',
  ],
  species: [],
  vehicles: [
    'https://swapi.info/api/vehicles/14',
    'https://swapi.info/api/vehicles/30',
  ],
  starships: [
    'https://swapi.info/api/starships/12',
    'https://swapi.info/api/starships/22',
  ],
  created: '2014-12-20T21:17:56.891000Z',
  url: 'https://swapi.info/api/people/1',
}, {
  name: 'Person6',
  height: '172',
  mass: '77',
  hair_color: 'blond',
  skin_color: 'fair',
  eye_color: 'blue',
  birth_year: '19BBY',
  gender: 'male',
  homeworld: 'https://swapi.info/api/planets/1',
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/6',
  ],
  species: [],
  vehicles: [
    'https://swapi.info/api/vehicles/14',
    'https://swapi.info/api/vehicles/30',
  ],
  starships: [
    'https://swapi.info/api/starships/12',
    'https://swapi.info/api/starships/22',
  ],
  created: '2014-12-20T21:17:56.891000Z',
  url: 'https://swapi.info/api/people/1',
}, {
  name: 'Person7',
  height: '172',
  mass: '77',
  hair_color: 'blond',
  skin_color: 'fair',
  eye_color: 'blue',
  birth_year: '19BBY',
  gender: 'male',
  homeworld: 'https://swapi.info/api/planets/1',
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/6',
  ],
  species: [],
  vehicles: [
    'https://swapi.info/api/vehicles/14',
    'https://swapi.info/api/vehicles/30',
  ],
  starships: [
    'https://swapi.info/api/starships/12',
    'https://swapi.info/api/starships/22',
  ],
  created: '2014-12-20T21:17:56.891000Z',
  url: 'https://swapi.info/api/people/1',
}, {
  name: 'Person8',
  height: '172',
  mass: '77',
  hair_color: 'blond',
  skin_color: 'fair',
  eye_color: 'blue',
  birth_year: '19BBY',
  gender: 'male',
  homeworld: 'https://swapi.info/api/planets/1',
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/6',
  ],
  species: [],
  vehicles: [
    'https://swapi.info/api/vehicles/14',
    'https://swapi.info/api/vehicles/30',
  ],
  starships: [
    'https://swapi.info/api/starships/12',
    'https://swapi.info/api/starships/22',
  ],
  created: '2014-12-20T21:17:56.891000Z',
  url: 'https://swapi.info/api/people/1',
}, {
  name: 'Person9',
  height: '172',
  mass: '77',
  hair_color: 'blond',
  skin_color: 'fair',
  eye_color: 'blue',
  birth_year: '19BBY',
  gender: 'male',
  homeworld: 'https://swapi.info/api/planets/1',
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/6',
  ],
  species: [],
  vehicles: [
    'https://swapi.info/api/vehicles/14',
    'https://swapi.info/api/vehicles/30',
  ],
  starships: [
    'https://swapi.info/api/starships/12',
    'https://swapi.info/api/starships/22',
  ],
  created: '2014-12-20T21:17:56.891000Z',
  url: 'https://swapi.info/api/people/1',
}, {
  name: 'Person11',
  height: '172',
  mass: '77',
  hair_color: 'blond',
  skin_color: 'fair',
  eye_color: 'blue',
  birth_year: '19BBY',
  gender: 'male',
  homeworld: 'https://swapi.info/api/planets/1',
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/6',
  ],
  species: [],
  vehicles: [
    'https://swapi.info/api/vehicles/14',
    'https://swapi.info/api/vehicles/30',
  ],
  starships: [
    'https://swapi.info/api/starships/12',
    'https://swapi.info/api/starships/22',
  ],
  created: '2014-12-20T21:17:56.891000Z',
  url: 'https://swapi.info/api/people/1',
}, {
  name: 'Person12',
  height: '172',
  mass: '77',
  hair_color: 'blond',
  skin_color: 'fair',
  eye_color: 'blue',
  birth_year: '19BBY',
  gender: 'male',
  homeworld: 'https://swapi.info/api/planets/1',
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/2',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/6',
  ],
  species: [],
  vehicles: [
    'https://swapi.info/api/vehicles/14',
    'https://swapi.info/api/vehicles/30',
  ],
  starships: [
    'https://swapi.info/api/starships/12',
    'https://swapi.info/api/starships/22',
  ],
  created: '2014-12-01T21:17:56.891000Z',
  url: 'https://swapi.info/api/people/1',
},
]
