import type { Planet } from '../../interfaces'

export const MOCKED_TATOOINE_PLANET = {
  name: 'Tatooine',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2014-12-09T14:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}

export const mockedPlanets: Planet[] = [
  MOCKED_TATOOINE_PLANET,
  {
    name: 'Planet2',
    rotation_period: '23',
    orbital_period: '304',
    diameter: '10465',
    climate: 'arid',
    gravity: '1 standard',
    terrain: 'desert',
    surface_water: '1',
    population: '200000',
    residents: [
      'https://swapi.info/api/people/1',
      'https://swapi.info/api/people/2',
      'https://swapi.info/api/people/4',
      'https://swapi.info/api/people/6',
      'https://swapi.info/api/people/7',
      'https://swapi.info/api/people/8',
      'https://swapi.info/api/people/9',
      'https://swapi.info/api/people/11',
      'https://swapi.info/api/people/43',
      'https://swapi.info/api/people/62',
    ],
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/4',
      'https://swapi.info/api/films/5',
      'https://swapi.info/api/films/6',
    ],
    created: '2014-11-09T13:50:49.641000Z',
    edited: '2014-12-09T13:50:49.641000Z',
    url: 'https://swapi.info/api/planets/1',
  },
  {
    name: 'Planet3',
    rotation_period: '23',
    orbital_period: '304',
    diameter: '10465',
    climate: 'arid',
    gravity: '1 standard',
    terrain: 'desert',
    surface_water: '1',
    population: '200000',
    residents: [
      'https://swapi.info/api/people/1',
      'https://swapi.info/api/people/2',
      'https://swapi.info/api/people/4',
      'https://swapi.info/api/people/6',
      'https://swapi.info/api/people/7',
      'https://swapi.info/api/people/8',
      'https://swapi.info/api/people/9',
      'https://swapi.info/api/people/11',
      'https://swapi.info/api/people/43',
      'https://swapi.info/api/people/62',
    ],
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/4',
      'https://swapi.info/api/films/5',
      'https://swapi.info/api/films/6',
    ],
    created: '2014-05-09T13:50:49.641000Z',
    edited: '2014-12-09T13:50:49.641000Z',
    url: 'https://swapi.info/api/planets/1',
  },
  {
    name: 'Planet4',
    rotation_period: '23',
    orbital_period: '304',
    diameter: '10465',
    climate: 'arid',
    gravity: '1 standard',
    terrain: 'desert',
    surface_water: '1',
    population: '200000',
    residents: [
      'https://swapi.info/api/people/1',
      'https://swapi.info/api/people/2',
      'https://swapi.info/api/people/4',
      'https://swapi.info/api/people/6',
      'https://swapi.info/api/people/7',
      'https://swapi.info/api/people/8',
      'https://swapi.info/api/people/9',
      'https://swapi.info/api/people/11',
      'https://swapi.info/api/people/43',
      'https://swapi.info/api/people/62',
    ],
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/4',
      'https://swapi.info/api/films/5',
      'https://swapi.info/api/films/6',
    ],
    created: '2014-12-21T13:50:49.641000Z',
    edited: '2014-12-09T13:50:49.641000Z',
    url: 'https://swapi.info/api/planets/1',
  },
  {
    name: 'Planet5',
    rotation_period: '23',
    orbital_period: '304',
    diameter: '10465',
    climate: 'arid',
    gravity: '1 standard',
    terrain: 'desert',
    surface_water: '1',
    population: '200000',
    residents: [
      'https://swapi.info/api/people/1',
      'https://swapi.info/api/people/2',
      'https://swapi.info/api/people/4',
      'https://swapi.info/api/people/6',
      'https://swapi.info/api/people/7',
      'https://swapi.info/api/people/8',
      'https://swapi.info/api/people/9',
      'https://swapi.info/api/people/11',
      'https://swapi.info/api/people/43',
      'https://swapi.info/api/people/62',
    ],
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/4',
      'https://swapi.info/api/films/5',
      'https://swapi.info/api/films/6',
    ],
    created: '2014-12-06T13:50:49.641000Z',
    edited: '2014-12-09T13:50:49.641000Z',
    url: 'https://swapi.info/api/planets/1',
  },
  {
    name: 'Planet6',
    rotation_period: '23',
    orbital_period: '304',
    diameter: '10465',
    climate: 'arid',
    gravity: '1 standard',
    terrain: 'desert',
    surface_water: '1',
    population: '200000',
    residents: [
      'https://swapi.info/api/people/1',
      'https://swapi.info/api/people/2',
      'https://swapi.info/api/people/4',
      'https://swapi.info/api/people/6',
      'https://swapi.info/api/people/7',
      'https://swapi.info/api/people/8',
      'https://swapi.info/api/people/9',
      'https://swapi.info/api/people/11',
      'https://swapi.info/api/people/43',
      'https://swapi.info/api/people/62',
    ],
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/4',
      'https://swapi.info/api/films/5',
      'https://swapi.info/api/films/6',
    ],
    created: '2014-03-09T13:50:49.641000Z',
    edited: '2014-12-09T13:50:49.641000Z',
    url: 'https://swapi.info/api/planets/1',
  },
  {
    name: 'Planet7',
    rotation_period: '23',
    orbital_period: '304',
    diameter: '10465',
    climate: 'arid',
    gravity: '1 standard',
    terrain: 'desert',
    surface_water: '1',
    population: '200000',
    residents: [
      'https://swapi.info/api/people/1',
      'https://swapi.info/api/people/2',
      'https://swapi.info/api/people/4',
      'https://swapi.info/api/people/6',
      'https://swapi.info/api/people/7',
      'https://swapi.info/api/people/8',
      'https://swapi.info/api/people/9',
      'https://swapi.info/api/people/11',
      'https://swapi.info/api/people/43',
      'https://swapi.info/api/people/62',
    ],
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/4',
      'https://swapi.info/api/films/5',
      'https://swapi.info/api/films/6',
    ],
    created: '2014-02-09T13:50:49.641000Z',
    edited: '2014-12-09T13:50:49.641000Z',
    url: 'https://swapi.info/api/planets/1',
  },
  {
    name: 'Planet8',
    rotation_period: '23',
    orbital_period: '304',
    diameter: '10465',
    climate: 'arid',
    gravity: '1 standard',
    terrain: 'desert',
    surface_water: '1',
    population: '200000',
    residents: [
      'https://swapi.info/api/people/1',
      'https://swapi.info/api/people/2',
      'https://swapi.info/api/people/4',
      'https://swapi.info/api/people/6',
      'https://swapi.info/api/people/7',
      'https://swapi.info/api/people/8',
      'https://swapi.info/api/people/9',
      'https://swapi.info/api/people/11',
      'https://swapi.info/api/people/43',
      'https://swapi.info/api/people/62',
    ],
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/4',
      'https://swapi.info/api/films/5',
      'https://swapi.info/api/films/6',
    ],
    created: '2011-12-09T13:50:49.641000Z',
    edited: '2014-12-09T13:50:49.641000Z',
    url: 'https://swapi.info/api/planets/1',
  },
  {
    name: 'Planet9',
    rotation_period: '23',
    orbital_period: '304',
    diameter: '10465',
    climate: 'arid',
    gravity: '1 standard',
    terrain: 'desert',
    surface_water: '1',
    population: '200000',
    residents: [
      'https://swapi.info/api/people/1',
      'https://swapi.info/api/people/2',
      'https://swapi.info/api/people/4',
      'https://swapi.info/api/people/6',
      'https://swapi.info/api/people/7',
      'https://swapi.info/api/people/8',
      'https://swapi.info/api/people/9',
      'https://swapi.info/api/people/11',
      'https://swapi.info/api/people/43',
      'https://swapi.info/api/people/62',
    ],
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/4',
      'https://swapi.info/api/films/5',
      'https://swapi.info/api/films/6',
    ],
    created: '2004-12-09T13:50:49.641000Z',
    edited: '2014-12-09T13:50:49.641000Z',
    url: 'https://swapi.info/api/planets/1',
  },
  {
    name: 'Planet10',
    rotation_period: '23',
    orbital_period: '304',
    diameter: '10465',
    climate: 'arid',
    gravity: '1 standard',
    terrain: 'desert',
    surface_water: '1',
    population: '200000',
    residents: [
      'https://swapi.info/api/people/1',
      'https://swapi.info/api/people/2',
      'https://swapi.info/api/people/4',
      'https://swapi.info/api/people/6',
      'https://swapi.info/api/people/7',
      'https://swapi.info/api/people/8',
      'https://swapi.info/api/people/9',
      'https://swapi.info/api/people/11',
      'https://swapi.info/api/people/43',
      'https://swapi.info/api/people/62',
    ],
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/4',
      'https://swapi.info/api/films/5',
      'https://swapi.info/api/films/6',
    ],
    created: '2015-12-09T13:50:49.641000Z',
    edited: '2014-12-09T13:50:49.641000Z',
    url: 'https://swapi.info/api/planets/1',
  },
  {
    name: 'Planet11',
    rotation_period: '23',
    orbital_period: '304',
    diameter: '10465',
    climate: 'arid',
    gravity: '1 standard',
    terrain: 'desert',
    surface_water: '1',
    population: '200000',
    residents: [
      'https://swapi.info/api/people/1',
      'https://swapi.info/api/people/2',
      'https://swapi.info/api/people/4',
      'https://swapi.info/api/people/6',
      'https://swapi.info/api/people/7',
      'https://swapi.info/api/people/8',
      'https://swapi.info/api/people/9',
      'https://swapi.info/api/people/11',
      'https://swapi.info/api/people/43',
      'https://swapi.info/api/people/62',
    ],
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/4',
      'https://swapi.info/api/films/5',
      'https://swapi.info/api/films/6',
    ],
    created: '2014-12-22T13:50:49.641000Z',
    edited: '2014-12-09T13:50:49.641000Z',
    url: 'https://swapi.info/api/planets/1',
  },
  {
    name: 'Planet12',
    rotation_period: '23',
    orbital_period: '304',
    diameter: '10465',
    climate: 'arid',
    gravity: '1 standard',
    terrain: 'desert',
    surface_water: '1',
    population: '200000',
    residents: [
      'https://swapi.info/api/people/1',
      'https://swapi.info/api/people/2',
      'https://swapi.info/api/people/4',
      'https://swapi.info/api/people/6',
      'https://swapi.info/api/people/7',
      'https://swapi.info/api/people/8',
      'https://swapi.info/api/people/9',
      'https://swapi.info/api/people/11',
      'https://swapi.info/api/people/43',
      'https://swapi.info/api/people/62',
    ],
    films: [
      'https://swapi.info/api/films/1',
      'https://swapi.info/api/films/3',
      'https://swapi.info/api/films/4',
      'https://swapi.info/api/films/5',
      'https://swapi.info/api/films/6',
    ],
    created: '2014-12-24T13:50:49.641000Z',
    edited: '2014-12-09T13:50:49.641000Z',
    url: 'https://swapi.info/api/planets/1',
  },
]

export const FILTERED_PLANETS_TEST_CASES = [
  {
    searchedName: 'planet1',
    expected: [
      {
        name: 'Planet10',
        rotation_period: '23',
        orbital_period: '304',
        diameter: '10465',
        climate: 'arid',
        gravity: '1 standard',
        terrain: 'desert',
        surface_water: '1',
        population: '200000',
        residents: [
          'https://swapi.info/api/people/1',
          'https://swapi.info/api/people/2',
          'https://swapi.info/api/people/4',
          'https://swapi.info/api/people/6',
          'https://swapi.info/api/people/7',
          'https://swapi.info/api/people/8',
          'https://swapi.info/api/people/9',
          'https://swapi.info/api/people/11',
          'https://swapi.info/api/people/43',
          'https://swapi.info/api/people/62',
        ],
        films: [
          'https://swapi.info/api/films/1',
          'https://swapi.info/api/films/3',
          'https://swapi.info/api/films/4',
          'https://swapi.info/api/films/5',
          'https://swapi.info/api/films/6',
        ],
        created: '2015-12-09T13:50:49.641000Z',
        edited: '2014-12-09T13:50:49.641000Z',
        url: 'https://swapi.info/api/planets/1',
      },
      {
        name: 'Planet11',
        rotation_period: '23',
        orbital_period: '304',
        diameter: '10465',
        climate: 'arid',
        gravity: '1 standard',
        terrain: 'desert',
        surface_water: '1',
        population: '200000',
        residents: [
          'https://swapi.info/api/people/1',
          'https://swapi.info/api/people/2',
          'https://swapi.info/api/people/4',
          'https://swapi.info/api/people/6',
          'https://swapi.info/api/people/7',
          'https://swapi.info/api/people/8',
          'https://swapi.info/api/people/9',
          'https://swapi.info/api/people/11',
          'https://swapi.info/api/people/43',
          'https://swapi.info/api/people/62',
        ],
        films: [
          'https://swapi.info/api/films/1',
          'https://swapi.info/api/films/3',
          'https://swapi.info/api/films/4',
          'https://swapi.info/api/films/5',
          'https://swapi.info/api/films/6',
        ],
        created: '2014-12-22T13:50:49.641000Z',
        edited: '2014-12-09T13:50:49.641000Z',
        url: 'https://swapi.info/api/planets/1',
      },
      {
        name: 'Planet12',
        rotation_period: '23',
        orbital_period: '304',
        diameter: '10465',
        climate: 'arid',
        gravity: '1 standard',
        terrain: 'desert',
        surface_water: '1',
        population: '200000',
        residents: [
          'https://swapi.info/api/people/1',
          'https://swapi.info/api/people/2',
          'https://swapi.info/api/people/4',
          'https://swapi.info/api/people/6',
          'https://swapi.info/api/people/7',
          'https://swapi.info/api/people/8',
          'https://swapi.info/api/people/9',
          'https://swapi.info/api/people/11',
          'https://swapi.info/api/people/43',
          'https://swapi.info/api/people/62',
        ],
        films: [
          'https://swapi.info/api/films/1',
          'https://swapi.info/api/films/3',
          'https://swapi.info/api/films/4',
          'https://swapi.info/api/films/5',
          'https://swapi.info/api/films/6',
        ],
        created: '2014-12-24T13:50:49.641000Z',
        edited: '2014-12-09T13:50:49.641000Z',
        url: 'https://swapi.info/api/planets/1',
      },
    ],
  },
  {
    searchedName: 'TAT',
    expected: [MOCKED_TATOOINE_PLANET],
  },
]

export const FILTERED_SORTED_PLANETS_TEST_CASES = [
  {
    searchedName: 'planet1',
    expected: [
      {
        name: 'Planet11',
        rotation_period: '23',
        orbital_period: '304',
        diameter: '10465',
        climate: 'arid',
        gravity: '1 standard',
        terrain: 'desert',
        surface_water: '1',
        population: '200000',
        residents: [
          'https://swapi.info/api/people/1',
          'https://swapi.info/api/people/2',
          'https://swapi.info/api/people/4',
          'https://swapi.info/api/people/6',
          'https://swapi.info/api/people/7',
          'https://swapi.info/api/people/8',
          'https://swapi.info/api/people/9',
          'https://swapi.info/api/people/11',
          'https://swapi.info/api/people/43',
          'https://swapi.info/api/people/62',
        ],
        films: [
          'https://swapi.info/api/films/1',
          'https://swapi.info/api/films/3',
          'https://swapi.info/api/films/4',
          'https://swapi.info/api/films/5',
          'https://swapi.info/api/films/6',
        ],
        created: '2014-12-22T13:50:49.641000Z',
        edited: '2014-12-09T13:50:49.641000Z',
        url: 'https://swapi.info/api/planets/1',
      }, {
        name: 'Planet12',
        rotation_period: '23',
        orbital_period: '304',
        diameter: '10465',
        climate: 'arid',
        gravity: '1 standard',
        terrain: 'desert',
        surface_water: '1',
        population: '200000',
        residents: [
          'https://swapi.info/api/people/1',
          'https://swapi.info/api/people/2',
          'https://swapi.info/api/people/4',
          'https://swapi.info/api/people/6',
          'https://swapi.info/api/people/7',
          'https://swapi.info/api/people/8',
          'https://swapi.info/api/people/9',
          'https://swapi.info/api/people/11',
          'https://swapi.info/api/people/43',
          'https://swapi.info/api/people/62',
        ],
        films: [
          'https://swapi.info/api/films/1',
          'https://swapi.info/api/films/3',
          'https://swapi.info/api/films/4',
          'https://swapi.info/api/films/5',
          'https://swapi.info/api/films/6',
        ],
        created: '2014-12-24T13:50:49.641000Z',
        edited: '2014-12-09T13:50:49.641000Z',
        url: 'https://swapi.info/api/planets/1',
      }, {
        name: 'Planet10',
        rotation_period: '23',
        orbital_period: '304',
        diameter: '10465',
        climate: 'arid',
        gravity: '1 standard',
        terrain: 'desert',
        surface_water: '1',
        population: '200000',
        residents: [
          'https://swapi.info/api/people/1',
          'https://swapi.info/api/people/2',
          'https://swapi.info/api/people/4',
          'https://swapi.info/api/people/6',
          'https://swapi.info/api/people/7',
          'https://swapi.info/api/people/8',
          'https://swapi.info/api/people/9',
          'https://swapi.info/api/people/11',
          'https://swapi.info/api/people/43',
          'https://swapi.info/api/people/62',
        ],
        films: [
          'https://swapi.info/api/films/1',
          'https://swapi.info/api/films/3',
          'https://swapi.info/api/films/4',
          'https://swapi.info/api/films/5',
          'https://swapi.info/api/films/6',
        ],
        created: '2015-12-09T13:50:49.641000Z',
        edited: '2014-12-09T13:50:49.641000Z',
        url: 'https://swapi.info/api/planets/1',
      },
    ],
  },
  {
    searchedName: 'TAT',
    expected: [MOCKED_TATOOINE_PLANET],
  },
]

export const EXPECTED_SORTED_PLANETS_NAME_ASCENDING = [{
  name: 'Planet10',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2015-12-09T13:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}, {
  name: 'Planet11',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2014-12-22T13:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}, {
  name: 'Planet12',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2014-12-24T13:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}, {
  name: 'Planet2',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2014-11-09T13:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}, {
  name: 'Planet3',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2014-05-09T13:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}, {
  name: 'Planet4',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2014-12-21T13:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}, {
  name: 'Planet5',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2014-12-06T13:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}, {
  name: 'Planet6',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2014-03-09T13:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}, {
  name: 'Planet7',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2014-02-09T13:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}, {
  name: 'Planet8',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2011-12-09T13:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}, {
  name: 'Planet9',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2004-12-09T13:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}, MOCKED_TATOOINE_PLANET]

export const EXPECTED_SORTED_PLANETS_NAME_DESCENDING = [...EXPECTED_SORTED_PLANETS_NAME_ASCENDING].reverse()

export const EXPECTED_SORTED_PLANETS_DATE_ASCENDING = [{
  name: 'Planet9',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2004-12-09T13:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}, {
  name: 'Planet8',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2011-12-09T13:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}, {
  name: 'Planet7',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2014-02-09T13:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}, {
  name: 'Planet6',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2014-03-09T13:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}, {
  name: 'Planet3',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2014-05-09T13:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}, {
  name: 'Planet2',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2014-11-09T13:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}, {
  name: 'Planet5',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2014-12-06T13:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}, MOCKED_TATOOINE_PLANET, {
  name: 'Planet4',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2014-12-21T13:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}, {
  name: 'Planet11',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2014-12-22T13:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}, {
  name: 'Planet12',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2014-12-24T13:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}, {
  name: 'Planet10',
  rotation_period: '23',
  orbital_period: '304',
  diameter: '10465',
  climate: 'arid',
  gravity: '1 standard',
  terrain: 'desert',
  surface_water: '1',
  population: '200000',
  residents: [
    'https://swapi.info/api/people/1',
    'https://swapi.info/api/people/2',
    'https://swapi.info/api/people/4',
    'https://swapi.info/api/people/6',
    'https://swapi.info/api/people/7',
    'https://swapi.info/api/people/8',
    'https://swapi.info/api/people/9',
    'https://swapi.info/api/people/11',
    'https://swapi.info/api/people/43',
    'https://swapi.info/api/people/62',
  ],
  films: [
    'https://swapi.info/api/films/1',
    'https://swapi.info/api/films/3',
    'https://swapi.info/api/films/4',
    'https://swapi.info/api/films/5',
    'https://swapi.info/api/films/6',
  ],
  created: '2015-12-09T13:50:49.641000Z',
  edited: '2014-12-09T13:50:49.641000Z',
  url: 'https://swapi.info/api/planets/1',
}]

export const EXPECTED_SORTED_PLANETS_DATE_DESCENDING = [...EXPECTED_SORTED_PLANETS_DATE_ASCENDING].reverse()
