/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Navigation: typeof import('./components/Navigation/Navigation.vue')['default']
    PeopleTable: typeof import('./components/PeopleTable/PeopleTable.vue')['default']
    PlanetsTable: typeof import('./components/PlanetsTable/PlanetsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchNameInput: typeof import('./components/SearchNameInput/SearchNameInput.vue')['default']
    SortButtons: typeof import('./components/SortButtons/SortButtons.vue')['default']
    TableWrapper: typeof import('./components/TableWrapper/TableWrapper.vue')['default']
    TitleComponent: typeof import('./components/TitleComponent/TitleComponent.vue')['default']
  }
}
